### ISSUE TITLE
IAST convention of MW72 for vocalic 'r'

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MW72#1]
Shalu submitted two corrections for MW72 under headword 'kara':

```
  kṛi   =>  kṛ
  vṛiddhi-kara  =>  vṛddhi-kara
```

I am not implementing these, as the coding  (kṛi , etc.) accurately reflect the scanned text of MW72.  The underlying problem is that MW72 uses a now non-standard IAST representation for vocalic 'r', 
namely 'ṛi' instead of 'ṛ'.

In MW (99), the same text convention is used.   And the same coding of text appears.  For instance,
under aMSu (slp1 spelling) at L=54, the underlying record of mw.xml is coded:

```
<c>N._of_a_<as0>R2ishi</as0><as1><s>fzi</s></as1></c>
```

So there is that 'R2ishi' as the original coding, as in MW72.  But, in MW, we went through a step
of creating a standardized spelling of this IAST text:  fzi.
And it is this standardized spelling (in the 'as1' element) that is shown in displays. So, if you ask for Roman Unicode
display in MW you see standard IAST:

```
N. of a ṛṣi
```

We aren't ready to tackle 'normalizing' the dictionaries with respect to IAST (as was done with MW).
I think this should be done systematically, whenever it is done.

**Comment by drdhaval2785** [comment]
Corrections done.
