### ISSUE TITLE
Unfilled </lang> cases

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MW72#5]
@funderburkjim 

Noticed few unfilled tag cases, and filled those as per the print text.
[Base file is the mw72.txt from csl-orig\v02]

Some of these (which are split across lines in print) are put in a single line in digitization but leaving the next line tags as is. These could either be split as in print or the next line tags are to be removed.

At one or two places, the Arabic script is marked as Greek.

As the html diff file could not be uploaded here, made a zip and also a pdf of the same is made.
[mw72 unfilled lang.zip](https://github.com/sanskrit-lexicon/MW72/files/7686499/mw72.unfilled.lang.zip)
[mw72 unfilled lang.pdf](https://github.com/sanskrit-lexicon/MW72/files/7686500/mw72.unfilled.lang.pdf)

**Comment by Andhrabharati** [comment]
In the process, seen that few Greek accents are wrongly marked.
Probably another full reading of the Greek words might be better.

**Comment by Andhrabharati** [comment]
Incidentally, surprising that these mw72 cases are not listed by @funderburkjim in the "texts with greek (greek NOT DONE)"!!
https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/36#issuecomment-917063769

**Comment by Andhrabharati** [comment]
If @funderburkjim takes the Greek letters from my INM file (as he has started looking at my work there), then just three works remain to be filled for Greek- BEN, BOP and BUR.

I would be taking up BEN next.

**Comment by gasyoun** [comment]
> At one or two places, the Arabic script is marked as Greek.

Eagle-eyed one.

> In the process, seen that few Greek accents are wrongly marked.

Not noted?

> just three works remain to be filled for Greek- BEN, BOP and BUR.

Thanks for the update of Greek status
